spring:
  name: demo-security
  jpa:
    show-sql: true
    # hibernate:
    # ddl-auto: update
  datasource:
    driverClassName:
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=demo-security
    username: sa
    password: ${DB_PASSWORD}
jwt:
  key: ${JWT_KEY}
  access-token-expiration: ${JWT_HOUR_ONE} # 1 hour || 60000 # 1 minute
  refresh-token-expiration: ${JWT_DAY}  # 24 hour
